#!/bin/sh
set -eu

: "${SANTET_TEST_DOCKER_LOG:?SANTET_TEST_DOCKER_LOG is required}"
: > "$SANTET_TEST_DOCKER_LOG"
for argument in "$@"; do
  printf '%s\n' "$argument" >> "$SANTET_TEST_DOCKER_LOG"
done
